<?php

/**
 * @file
 */
include_once 'mistura_admin.features.inc';


/**
 * Constant for Administrator Role ID.
 */
define('ROLE_ADMIN', 3);

/**
 * Implements hook_permission().
 */
function mistura_admin_permission() {
  return array(
    'acessar mistura admin' => array(
      'title' => t('Acessar administração do website'),
    ),
    'administrar mistura' => array(
      'title' => t('Administrar o website'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mistura_admin_menu() {

  $items = array();

  $items['admin/mistura'] = array(
    'title' => 'Mistura',
    'description' => 'Dashboard de administração',
    'page callback' => 'mistura_admin_dashboard',
    'access callback' => 'user_access',
    'access arguments' => array('acessar mistura admin'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/pages.inc',
  );

  $items['admin/mistura/settings'] = array(
    'title' => 'Configurações',
    'description' => 'Configurações do website',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mistura_admin_settings'),
    'access arguments' => array('administrar mistura'),
    'file' => 'includes/admin.inc',
		'menu_name' => 'menu-admin-menu',
		'weight' => 48
  );
  
  $items['user/edit'] = array(
    'title' => 'Minha conta',
    'page callback' => 'mistura_admin_redirect_user_edit',
    'access arguments' => array('acessar mistura admin'),
    'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/admin.inc',
    'menu_name' => 'menu-admin-menu',
    'weight' => 49
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function mistura_admin_init() {
  
  $contexts = context_active_contexts();
  
  if (array_key_exists('mistura_admin_sitewide', $contexts)) {
    drupal_add_js(drupal_get_path('module', 'mistura_admin') . '/js/mistura_admin.js', array('group' => JS_THEME, 'every_page' => TRUE));
    drupal_add_css(drupal_get_path('module', 'mistura_admin') . '/css/mistura_admin.css', array('group' => CSS_THEME, 'every_page' => TRUE));
  }

  // jQuery Easing Plugin.
  // @link http://gsgd.co.uk/sandbox/jquery/easing/
  if ($path = libraries_get_path('jquery.easing')) {
    drupal_add_js($path . '/jquery.easing.1.3.min.js', array('group' => JS_LIBRARY, 'every_page' => TRUE));
  }

  // jQuery HoverIntent Plugin.
  // @link http://cherne.net/brian/resources/jquery.hoverIntent.html
  if ($path = libraries_get_path('jquery.hoverIntent')) {
    drupal_add_js($path . '/jquery.hoverIntent.r6.min.js', array('group' => JS_LIBRARY, 'every_page' => TRUE));
  }

  // jQuery ScrollTo Plugin.
  // @link http://demos.flesler.com/jquery/scrollTo/
  if ($path = libraries_get_path('jquery.scrollto')) {
    drupal_add_js($path . '/jquery.scrollTo-1.4.2-min.js', array('group' => JS_LIBRARY, 'every_page' => TRUE));
  }

  // jQuery Cycle Plugin.
  if ($path = libraries_get_path('jquery.cycle')) {
    drupal_add_js($path . '/jquery.cycle.min.js', array('group' => JS_LIBRARY, 'every_page' => TRUE));
  }
}

/**
 * Implements hook_preprocess().
 *
 * Adds an extra class to Admin menu items.
 */
function mistura_admin_preprocess_menu_link(&$variables) {
  if (isset($variables['element']['#theme']) && $variables['element']['#theme'] === 'menu_link__menu_admin_menu') {
    $classname = array_pop(explode('/', $variables['element']['#href']));
    $variables['element']['#attributes']['class'][] = $classname;
  }
}

/**
 * Implements hook_block_info().
 */
function mistura_admin_block_info() {
  $blocks['mistura_admin_menu'] = array(
    'info' => t('Features admin menu'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mistura_admin_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'mistura_admin_menu':
      $block['subject'] = '';
      $block['content'] = mistura_admin_get_menu_admin();
      break;
  }
  return $block;
}

/**
 * Generate a new nice_menu based on admin_menu
 * 
 * @return html  
 */
function mistura_admin_get_menu_admin() {
  $variables = array(
    'id' => 'mistura_admin_menu',
    'menu_name' => 'menu-admin-menu',
    'direction' => 'right',
    'depth' => -1
  );
  $output = theme('nice_menus', $variables);
  return $output['content'];
}

/**
 * Implements hook_form_alter().
 */
function mistura_admin_form_alter(&$form, &$form_state, $form_id) {
  unset($form['actions']['preview']);
}

/**
 * Implements hook_user_login
 */
function mistura_admin_user_login(&$edit, $account) {
  if (empty($_GET['destination']) && (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset')) {
    drupal_goto('admin/mistura');
  }
}