<?php
/**
 * @file
 * Code for the mistura_website feature.
 */

include_once 'mistura_website.features.inc';

/**
 * Implements hook_init().
 */
function mistura_website_init() {
	drupal_add_js(drupal_get_path('module', 'mistura_website') . '/js/mistura_website.js');
	drupal_add_css(drupal_get_path('module', 'mistura_website') . '/css/mistura_website.css');

}

/**
 * Implements hook_block_info().
 */
function mistura_website_block_info() {
	module_load_include('inc', 'mistura_admin', 'includes/admin');
	$blocos = mistura_admin_retorna_blocos_info();
	foreach ($blocos as $index => $bloco) {
		$blocks[$index] = array(
			'info'  => t($bloco['title']),
			'cache' => DRUPAL_NO_CACHE,
		);
	}

	$blocks['mistura_redes_sociais'] = array(
		'info'  => 'Redes sociais',
		'cache' => DRUPAL_NO_CACHE
	);

	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mistura_website_block_view($delta = '') {

	$block            = array();
	$block['subject'] = '';
	$block['content'] = '';

	if ($delta == 'mistura_redes_sociais') {

		$block['subject'] = 'Redes Sociais';

		module_load_include('inc', 'mistura_admin', 'includes/admin');
		$redes_sociais = mistura_admin_retorna_redes_sociais();
		$lista         = array();

		$count = 0;
		foreach ($redes_sociais as $social_index_name => $rede_social) {
			$url_rede_social = variable_get($social_index_name, '');
			if (!empty($url_rede_social)) {
				$lista[$count]['data']   = l($rede_social['titulo'], $url_rede_social, array('html' => TRUE, 'attributes' => array('title' => $rede_social['titulo'], 'target' => '_blank')));
				$lista[$count]['classe'] = 'social-icon ' . $social_index_name;
				$count++;
			}
		}
		$content = '';
		if (sizeof($lista) > 0) {
			$content = theme('item_list', array('items' => $lista));
		}
		$block['content'] = $content;

	}
	else {
		$block['subject'] = '';
		$block['content'] = variable_get($delta, '');
	}

	return $block;
}

/**
 * Implements hook_form_alter().
 */
function mistura_website_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id === 'webform_client_form_3') {
		//krumo($form);
	}

}